
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from PIL import Image, ImageTk
import guidef
import main2
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:/Users/Dell/Desktop/gui/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

image = Image.open("images/test0.jpg")
photo = ImageTk.PhotoImage(image)  # 转换为 tk.PhotoImage 格式
old_file_path = 'images/test0.jpg'
print(old_file_path)

window.geometry("413x604")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 604,
    width = 413,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    413.0,
    604.0,
    fill="#E3E3E3",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    206.0,
    237.0,
    image=photo
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    273.0,
    39.5,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=197.0,
    y=27.0,
    width=152.0,
    height=23.0
)

canvas.create_text(
    49.0,
    27.0,
    anchor="nw",
    text="输入你的名字",
    fill="#000000",
    font=("Inter", 20 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))#打开摄像头
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=main2.main2,
    relief="flat"
)
button_1.place(
    x=44.0,
    y=437.0,
    width=157.0,
    height=48.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))#刷新图片
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=guidef.showcamerapic,
    relief="flat"
)
button_2.place(
    x=206.0,
    y=437.0,
    width=157.0,
    height=48.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))#录入人脸
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: guidef.on_button_click(old_file_path),
    relief="flat"
)
button_3.place(
    x=206.0,
    y=495.0,
    width=157.0,
    height=48.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))#本地照片
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: guidef.showfilepic,
    relief="flat"
)
button_4.place(
    x=44.0,
    y=495.0,
    width=157.0,
    height=48.0
)

window.resizable(False, False)
window.mainloop()
